// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.9.0.77
//      SpecFlow Generator Version:1.9.0.0
//      Runtime Version:4.0.30319.18046
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Specs.WhingePool
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.9.0.77")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Whinge")]
    public partial class WhingeFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Whinge.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Whinge", "As a whinger, I would like to whinge to a whinge pool", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 4
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "StorageAccount",
                        "StorageAccountKey"});
            table1.AddRow(new string[] {
                        "myobpdqaart",
                        "MHDYieseAgGX6HbE8yWK4e0L2eKkUt+an6UbX1/6o0nC2FK2pmgxi/OVW+WEVyH50ROBRMtw0wxf057KD" +
                            "TaDfA=="});
#line 5
 testRunner.Given("An Azure Storage Configuration of", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "ScheduledTasksQueueName",
                        "RegisteredHandlersTableName",
                        "RegisteredHandlersBlobContainerName",
                        "RuntimeErrorsTableName"});
            table2.AddRow(new string[] {
                        "whingepool-test-scheduled-task-queue",
                        "WhingePoolHandlers",
                        "whingepool-handler-assemblies",
                        "WhingePoolRuntimeErrors"});
#line 9
 testRunner.And("A Pegasus Configuration of", ((string)(null)), table2, "And ");
#line hidden
            TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                        "WhingesTableName",
                        "WhingersTableName",
                        "WhingePoolsTableName",
                        "WhingesByWhingerTableName",
                        "WhingesByWhingePoolTableName"});
            table3.AddRow(new string[] {
                        "Whinges",
                        "Whingers",
                        "WhingePools",
                        "WhingesByWhinger",
                        "WhingesByWhingePool"});
#line 13
 testRunner.And("A WhingePool Configuration of", ((string)(null)), table3, "And ");
#line 17
 testRunner.And("An WhingePoolApplicationContext", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 19
 testRunner.And("An Empty WhingersTable", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                        "TwitterHandle"});
            table4.AddRow(new string[] {
                        "johnazariah"});
#line 21
 testRunner.And("A Default Set Of Whingers", ((string)(null)), table4, "And ");
#line 25
 testRunner.And("An Empty WhingePoolsTable", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table5.AddRow(new string[] {
                        "Test"});
            table5.AddRow(new string[] {
                        "Work"});
            table5.AddRow(new string[] {
                        "Azure"});
#line 27
 testRunner.And("A Default Set Of WhingePools", ((string)(null)), table5, "And ");
#line hidden
            TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                        "TwitterHandle"});
            table6.AddRow(new string[] {
                        "johnazariah"});
#line 33
 testRunner.And("The Current Whinger", ((string)(null)), table6, "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Save a invalid Whinge of more than 150 characters to an existing WhingePool")]
        public virtual void SaveAInvalidWhingeOfMoreThan150CharactersToAnExistingWhingePool()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Save a invalid Whinge of more than 150 characters to an existing WhingePool", ((string[])(null)));
#line 37
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                        "Whinge",
                        "WhingePool"});
            table7.AddRow(new string[] {
                        "I would really like to learn to whinge properly. I really don\'t know how to keep " +
                            "it short enough for Whinger to accept. Why cannot I learn to whinge within a lim" +
                            "it of hundred and fifty characters?",
                        "Test"});
#line 38
 testRunner.When("A whinge is saved", ((string)(null)), table7, "When ");
#line 41
 testRunner.Then("An instance of \"WhingeTooLong\" exception should be thrown", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Save a valid Whinge to an existing WhingePool")]
        public virtual void SaveAValidWhingeToAnExistingWhingePool()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Save a valid Whinge to an existing WhingePool", ((string[])(null)));
#line 43
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                        "Whinge",
                        "WhingePool"});
            table8.AddRow(new string[] {
                        "This is a really common whinge!",
                        "Test"});
#line 44
 testRunner.When("A whinge is saved", ((string)(null)), table8, "When ");
#line 47
 testRunner.Then("The save should succeed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Save a valid Whinge to an non-existing WhingePool")]
        public virtual void SaveAValidWhingeToAnNon_ExistingWhingePool()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Save a valid Whinge to an non-existing WhingePool", ((string[])(null)));
#line 49
this.ScenarioSetup(scenarioInfo);
#line 4
this.FeatureBackground();
#line hidden
            TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                        "Whinge",
                        "WhingePool"});
            table9.AddRow(new string[] {
                        "I hate having to go to the gym in the cold",
                        "Exercise"});
#line 50
 testRunner.When("A whinge is saved", ((string)(null)), table9, "When ");
#line hidden
            TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name"});
            table10.AddRow(new string[] {
                        "Exercise"});
#line 53
 testRunner.Then("A WhingePool should be created", ((string)(null)), table10, "Then ");
#line 56
 testRunner.And("The save should succeed", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
